server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: true
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
