server:
  port: 7050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
